# INITIAL SETTINGS

seed: 12536
debug: False
save: False
fold: 0

dataset:
  data_path: "train.csv"
  num_workers: 8  # batch_size * ngpu
  batch_size: 8
  max_len: 512
  n_folds: 4

model:
  name: "microsoft/deberta-v3-base"
  checkpointing: True

train:
  epochs: 4
  min_lr: 1e-6
  weight_decay: 0.01
  eps: 1e-6
  betas: (0.9, 0.999)
  encoder_lr: 2e-5
  decoder_lr: 2e-5

