# INITIAL SETTINGS

dataset:
  data_path: 'train_df.csv'
  num_workers: 8
  tr_batch_size: 2
  vl_batch_size: 8
  max_len: 1024
  labels: ['cohesion', 'syntax', 'vocabulary', 'phraseology', 'grammar', 'conventions']

model:
  backbone_name: 'microsoft/deberta-v3-base'
  gradient_checkpointing: True
  pooling: 'mean'  # 'lstm', 'mean'
  saved_model_path: ''

  lstm_params:
    hidden_size: 1024
    dropout_rate: 0.1
    bidirectional: True

